/*
  seedReisen.js — vorgefertigte Reisen, einmalig pro Gerät eingespielt (Merker
  "chds-seeds-applied" pro seedKey). Fügt nur hinzu; gelöschte Seeds kommen nicht
  zurück; namens+startgleiche werden übersprungen.
  Enthält: Amsterdam, Südostanatolien (2 Hotels) und Nordsee/NL (Noordwijk).
  Nichts erfunden – Inhalte aus den abgestimmten Plänen/Angaben; Koordinaten der
  Hauptorte als Näherung, der Rest wird beim Verorten/Offline-Vorbereiten geholt.
*/

export const SEED_TRIPS = [
  {
    "id": "imp-ams-trip",
    "name": "Amsterdam & Umgebung",
    "region": "Amsterdam",
    "land": "Niederlande",
    "anreiseart": "auto",
    "von": "Celle",
    "nach": "Amsterdam",
    "hinweise": "Anne Frank Haus unbedingt vorab online buchen. Grachtenfahrt: Lovers Canal Cruises. Rückfahrt mit Mittagsstopp in Osnabrück.",
    "auto": {
      "km": "",
      "preis": 1.8,
      "verbrauch": 9
    },
    "stay": {
      "name": "Grand Hotel Amrâth Amsterdam",
      "adresse": "Prins Hendrikkade 108, Amsterdam",
      "checkin": "2026-11-04",
      "checkout": "2026-11-07"
    },
    "start": "2026-11-04",
    "end": "2026-11-07",
    "items": [
      {
        "id": "imp-ams-1",
        "kategorie": "sehenswuerdigkeit",
        "name": "Vesting Naarden (Sternfestung)",
        "gebiet": "Naarden, Niederlande",
        "info": "Sternförmige Festungsstadt – erster Stopp auf der Anfahrt von Celle.",
        "notiz": "",
        "mapsSuche": "Vesting Naarden (Sternfestung), Naarden, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-04",
        "order": 0,
        "lat": 52.2958,
        "lon": 5.1619
      },
      {
        "id": "imp-ams-2",
        "kategorie": "hotel",
        "name": "Check-in Grand Hotel Amrâth Amsterdam",
        "gebiet": "Amsterdam, Niederlande",
        "info": "Prins Hendrikkade 108. Check-in nach Ankunft in Amsterdam.",
        "notiz": "",
        "mapsSuche": "Check-in Grand Hotel Amrâth Amsterdam, Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-04",
        "order": 1,
        "lat": 52.3765,
        "lon": 4.902
      },
      {
        "id": "imp-ams-3",
        "kategorie": "sehenswuerdigkeit",
        "name": "Anne Frank Haus",
        "gebiet": "Amsterdam, Niederlande",
        "info": "VORAB ONLINE BUCHEN! Tickets sind schnell ausverkauft.",
        "notiz": "",
        "mapsSuche": "Anne Frank Haus, Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-05",
        "order": 0,
        "lat": 52.3752,
        "lon": 4.884
      },
      {
        "id": "imp-ams-4",
        "kategorie": "sehenswuerdigkeit",
        "name": "Amsterdam erkunden (Altstadt & Grachten)",
        "gebiet": "Amsterdam, Niederlande",
        "info": "Bummel durch Zentrum, Grachtengürtel, Jordaan.",
        "notiz": "",
        "mapsSuche": "Amsterdam erkunden (Altstadt & Grachten), Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-05",
        "order": 1,
        "lat": 52.3731,
        "lon": 4.8926
      },
      {
        "id": "imp-ams-5",
        "kategorie": "sehenswuerdigkeit",
        "name": "Grachtenfahrt – Lovers Canal Cruises",
        "gebiet": "Amsterdam, Niederlande",
        "info": "Bootstour über die Grachten.",
        "notiz": "",
        "mapsSuche": "Grachtenfahrt – Lovers Canal Cruises, Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-05",
        "order": 2,
        "lat": 52.3785,
        "lon": 4.9005
      },
      {
        "id": "imp-ams-6",
        "kategorie": "sehenswuerdigkeit",
        "name": "Haarlem – Grote Markt",
        "gebiet": "Haarlem, Niederlande",
        "info": "Historischer Marktplatz mit St.-Bavo-Kirche.",
        "notiz": "",
        "mapsSuche": "Haarlem – Grote Markt, Haarlem, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 0,
        "lat": 52.3813,
        "lon": 4.6367
      },
      {
        "id": "imp-ams-7",
        "kategorie": "sehenswuerdigkeit",
        "name": "Frans Hals Museum",
        "gebiet": "Haarlem, Niederlande",
        "info": "Goldenes Zeitalter, Werke von Frans Hals.",
        "notiz": "",
        "mapsSuche": "Frans Hals Museum, Haarlem, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 1,
        "lat": 52.3772,
        "lon": 4.633
      },
      {
        "id": "imp-ams-8",
        "kategorie": "restaurant",
        "name": "Jopenkerk (Brauerei in Kirche)",
        "gebiet": "Haarlem, Niederlande",
        "info": "Brauerei-Gasthaus in einer alten Kirche – Mittag/Pause.",
        "notiz": "",
        "mapsSuche": "Jopenkerk (Brauerei in Kirche), Haarlem, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 2,
        "lat": 52.382,
        "lon": 4.633
      },
      {
        "id": "imp-ams-9",
        "kategorie": "wanderung",
        "name": "Bloemendaal aan Zee – Dünenwanderung",
        "gebiet": "Bloemendaal aan Zee, Niederlande",
        "info": "Dünen- und Strandwanderung an der Nordseeküste.",
        "notiz": "",
        "mapsSuche": "Bloemendaal aan Zee – Dünenwanderung, Bloemendaal aan Zee, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 3,
        "lat": 52.41,
        "lon": 4.535
      },
      {
        "id": "imp-ams-10",
        "kategorie": "restaurant",
        "name": "Café Tijn Akersloot",
        "gebiet": "Bloemendaal aan Zee, Niederlande",
        "info": "Strandcafé zum Ausklang.",
        "notiz": "",
        "mapsSuche": "Café Tijn Akersloot, Bloemendaal aan Zee, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 4,
        "lat": 52.409,
        "lon": 4.536
      },
      {
        "id": "imp-ams-11",
        "kategorie": "restaurant",
        "name": "Osnabrück – Mittagessen (Rückfahrt)",
        "gebiet": "Osnabrück, Deutschland",
        "info": "Zwischenstopp auf dem Rückweg nach Celle.",
        "notiz": "",
        "mapsSuche": "Osnabrück – Mittagessen (Rückfahrt), Osnabrück, Deutschland",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-07",
        "order": 0,
        "lat": 52.279,
        "lon": 8.043
      }
    ],
    "days": {},
    "packing": [],
    "seedKey": "ams-nl-2026-11",
    "erledigt": false,
    "personen": 2
  },
  {
    "id": "imp-soa-trip",
    "name": "Rundreise Südostanatolien",
    "region": "Diyarbakır",
    "land": "Türkei",
    "anreiseart": "flug",
    "von": "",
    "nach": "Diyarbakır",
    "hinweise": "2 Personen · Bus, Minibus & Taxi · Kurs 1 € ≈ 56 TL. WICHTIG: Taxi für Rückflug (04.10., 02:30) am 03.10. über Hotel vorbestellen. NOVH-Bus Mardin→Diyarbakır (02.10., 14:00) prüfen/buchen. Hotels in Mardin früh buchen. Bargeld in kleinen Scheinen (50/100/200 TL). Rutschfeste Schuhe, bedeckende Kleidung für religiöse Stätten.",
    "auto": {
      "km": "",
      "preis": 1.8,
      "verbrauch": 9
    },
    "stay": {
      "name": "Mardin (Osmanlı Konağı) + Diyarbakır (Demir)",
      "adresse": "",
      "checkin": "2026-09-29",
      "checkout": "2026-10-04"
    },
    "start": "2026-09-29",
    "end": "2026-10-04",
    "items": [
      {
        "id": "imp-soa-2",
        "kategorie": "sehenswuerdigkeit",
        "name": "Große Moschee (Ulu Camii)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Große Moschee (Ulu Camii), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "nachmittags",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 0,
        "lat": 37.9128,
        "lon": 40.2378
      },
      {
        "id": "imp-soa-3",
        "kategorie": "restaurant",
        "name": "Hasan Paşa Hanı",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Kaffee im historischen Innenhof.",
        "notiz": "",
        "mapsSuche": "Hasan Paşa Hanı, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 1,
        "lat": 37.913,
        "lon": 40.2383
      },
      {
        "id": "imp-soa-4",
        "kategorie": "sehenswuerdigkeit",
        "name": "Armenische Kirche Surp Giragos",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Armenische Kirche Surp Giragos, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 2,
        "lat": 37.9143,
        "lon": 40.2358
      },
      {
        "id": "imp-soa-5",
        "kategorie": "sehenswuerdigkeit",
        "name": "Vier-Füße-Minarett (Dört Ayaklı Minare)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Vier-Füße-Minarett (Dört Ayaklı Minare), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 3,
        "lat": 37.9124,
        "lon": 40.2352
      },
      {
        "id": "imp-soa-6",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hevsel-Gärten (UNESCO-Welterbe)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Spaziergang durch die terrassierten Gärten am Tigris.",
        "notiz": "",
        "mapsSuche": "Hevsel-Gärten (UNESCO-Welterbe), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 4,
        "lat": 37.905,
        "lon": 40.245
      },
      {
        "id": "imp-soa-7",
        "kategorie": "aussicht",
        "name": "Sonnenuntergang Stadtmauer – Keçi Burcu",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Blick auf Hevsel-Gärten & Tigristal.",
        "notiz": "",
        "mapsSuche": "Sonnenuntergang Stadtmauer – Keçi Burcu, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "18:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 8,
        "lat": 37.906,
        "lon": 40.2415
      },
      {
        "id": "imp-soa-8",
        "kategorie": "restaurant",
        "name": "Abendessen in Sur (Ciğer/Diyarbakır-Kebab)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Abendessen in Sur (Ciğer/Diyarbakır-Kebab), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "abends",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 10,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-9",
        "kategorie": "sehenswuerdigkeit",
        "name": "Heimatort Batman besuchen",
        "gebiet": "Batman, Türkei",
        "info": "Familie/Bekannte treffen, frühes Mittagessen. Minibus ab Diyarbakır (Doğu İlçe Otogarı), 1:15 Std.",
        "notiz": "",
        "mapsSuche": "Heimatort Batman besuchen, Batman, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "09:00–12:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 1,
        "lat": 37.8812,
        "lon": 41.1351
      },
      {
        "id": "imp-soa-10",
        "kategorie": "fotospot",
        "name": "Malabadi-Brücke (Foto-Stopp)",
        "gebiet": "Silvan, Türkei",
        "info": "Größte Steinbogenbrücke der Welt (12. Jh.). 15 Min. Umweg, frei.",
        "notiz": "",
        "mapsSuche": "Malabadi-Brücke (Foto-Stopp), Silvan, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "12:15",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 0,
        "lat": 38.087,
        "lon": 41.025
      },
      {
        "id": "imp-soa-11",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hasankeyf – Arkeopark & Museum",
        "gebiet": "Hasankeyf, Türkei",
        "info": "Gepäck am Museum/Ticketcenter deponieren. Eintritt 3 €.",
        "notiz": "",
        "mapsSuche": "Hasankeyf – Arkeopark & Museum, Hasankeyf, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "13:30–16:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 2,
        "lat": 37.7146,
        "lon": 41.414
      },
      {
        "id": "imp-soa-12",
        "kategorie": "sehenswuerdigkeit",
        "name": "Tigris-Bootstour Hasankeyf",
        "gebiet": "Hasankeyf, Türkei",
        "info": "1–1,5 Std., vor Ort am Steg buchen.",
        "notiz": "",
        "mapsSuche": "Tigris-Bootstour Hasankeyf, Hasankeyf, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 3,
        "lat": 37.7146,
        "lon": 41.414
      },
      {
        "id": "imp-soa-14",
        "kategorie": "sehenswuerdigkeit",
        "name": "Abendspaziergang Eski Midyat (Alt-Midyat)",
        "gebiet": "Midyat, Türkei",
        "info": "Verlassene Höhlenhäuser & versteckte Kirchen. Frei, ~30 Min.",
        "notiz": "",
        "mapsSuche": "Abendspaziergang Eski Midyat (Alt-Midyat), Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "18:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 3,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-15",
        "kategorie": "restaurant",
        "name": "Abendessen Gelüşke Hanı",
        "gebiet": "Midyat, Türkei",
        "info": "Historisches Ambiente.",
        "notiz": "",
        "mapsSuche": "Abendessen Gelüşke Hanı, Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 4,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-16",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kloster Mor Gabriel (Syrisch-Orthodox)",
        "gebiet": "Midyat, Türkei",
        "info": "Taxi ab Hotel (Festpreis 2.000–2.500 TL inkl. 1,5 Std. Wartezeit). Eintritt 200–300 TL p.P.; Knie/Schultern bedeckt.",
        "notiz": "",
        "mapsSuche": "Kloster Mor Gabriel (Syrisch-Orthodox), Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "09:00–10:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 0,
        "lat": 37.34,
        "lon": 41.472
      },
      {
        "id": "imp-soa-17",
        "kategorie": "sehenswuerdigkeit",
        "name": "Midyat – Konuk Evi & Telkari-Gassen",
        "gebiet": "Midyat, Türkei",
        "info": "Silberschmiede (Telkari), Konuk Evi 100 TL.",
        "notiz": "",
        "mapsSuche": "Midyat – Konuk Evi & Telkari-Gassen, Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "11:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 1,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-18",
        "kategorie": "restaurant",
        "name": "Mittagessen Midyat Aş Evi",
        "gebiet": "Midyat, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Mittagessen Midyat Aş Evi, Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "12:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 2,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-19",
        "kategorie": "hotel",
        "name": "Check-in Mardin – Osmanlı Konağı",
        "gebiet": "Mardin, Türkei",
        "info": "Minibus Midyat→Mardin 13:30 (1:15, 195–250 TL p.P.).",
        "notiz": "",
        "mapsSuche": "Check-in Hotel Mardin Altstadt (1. Cadde), Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "14:45",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 4,
        "lat": 37.3125,
        "lon": 40.737
      },
      {
        "id": "imp-soa-20",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kasımiye-Medrese & Kırklar-Kirche",
        "gebiet": "Mardin, Türkei",
        "info": "Kasımiye 80 TL, Kırklar 70 TL.",
        "notiz": "",
        "mapsSuche": "Kasımiye-Medrese & Kırklar-Kirche, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "15:00–16:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 0,
        "lat": 37.3075,
        "lon": 40.726
      },
      {
        "id": "imp-soa-21",
        "kategorie": "aussicht",
        "name": "Zinciriye-Medrese – Sonnenuntergang & Panorama",
        "gebiet": "Mardin, Türkei",
        "info": "Panoramablick über die mesopotamische Tiefebene. Eintritt 100 TL.",
        "notiz": "",
        "mapsSuche": "Zinciriye-Medrese – Sonnenuntergang & Panorama, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:00–18:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 2,
        "lat": 37.3135,
        "lon": 40.7385
      },
      {
        "id": "imp-soa-22",
        "kategorie": "restaurant",
        "name": "Abendessen Dachterrasse 1. Cadde",
        "gebiet": "Mardin, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Abendessen Dachterrasse 1. Cadde, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "abends",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 5,
        "lat": 37.3125,
        "lon": 40.737
      },
      {
        "id": "imp-soa-23",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kloster Deyrulzafaran (Safran-Kloster)",
        "gebiet": "Mardin, Türkei",
        "info": "Taxirunde Festpreis 3.500–4.000 TL inkl. Wartezeiten & Otogar. Führung & unterirdischer Sonnentempel. 200–300 TL p.P.",
        "notiz": "",
        "mapsSuche": "Kloster Deyrulzafaran (Safran-Kloster), Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "08:15",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 1,
        "lat": 37.307,
        "lon": 40.788
      },
      {
        "id": "imp-soa-24",
        "kategorie": "sehenswuerdigkeit",
        "name": "Savur",
        "gebiet": "Savur, Türkei",
        "info": "Authentisches kurdisches Städtchen mit jüdischer Synagoge (eine der ältesten der Türkei). ~1 Std. Stopp, frei.",
        "notiz": "",
        "mapsSuche": "Savur, Savur, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 0,
        "lat": 37.548,
        "lon": 40.895
      },
      {
        "id": "imp-soa-25",
        "kategorie": "sehenswuerdigkeit",
        "name": "Antike Stadt Dara",
        "gebiet": "Oğuz, Mardin, Türkei",
        "info": "Zisternen & Felsnekropole (falls Zeit bleibt), frei.",
        "notiz": "",
        "mapsSuche": "Antike Stadt Dara, Oğuz, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 1,
        "lat": 37.177,
        "lon": 40.948
      },
      {
        "id": "imp-soa-26",
        "kategorie": "restaurant",
        "name": "Mittagessen Yenişehir (Mardin Çırağan)",
        "gebiet": "Mardin, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Mittagessen Yenişehir (Mardin Çırağan), Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "13:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 3,
        "lat": 37.328,
        "lon": 40.735
      },
      {
        "id": "imp-soa-27",
        "kategorie": "hotel",
        "name": "Check-in Diyarbakır – Demir Hotel",
        "gebiet": "Diyarbakır, Türkei",
        "info": "NOVH-Bus Mardin→Diyarbakır 14:00 (1:20, 420–500 TL p.P.).",
        "notiz": "",
        "mapsSuche": "Check-in Hotel Diyarbakır, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "15:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 3,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-28",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hamam-Besuch (Abend)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Entspannter Abend in Diyarbakır.",
        "notiz": "",
        "mapsSuche": "Hamam-Besuch (Abend), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "abends",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 4,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-29",
        "kategorie": "sehenswuerdigkeit",
        "name": "Römisches Grenzkastell Zerzevan Kalesi",
        "gebiet": "Çınar, Diyarbakır, Türkei",
        "info": "Inkl. Mithras-Heiligtum. Anfahrt Stadtbus ÇM (KentKart) ab Doğu İlçe Garajı.",
        "notiz": "",
        "mapsSuche": "Römisches Grenzkastell Zerzevan Kalesi, Çınar, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "10:00–12:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 2,
        "lat": 37.552,
        "lon": 40.48
      },
      {
        "id": "imp-soa-30",
        "kategorie": "restaurant",
        "name": "Mittagessen Altstadt Diyarbakır",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Mittagessen Altstadt Diyarbakır, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "13:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 7,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-31",
        "kategorie": "sehenswuerdigkeit",
        "name": "İçkale – Ahmed Arif Literaturmuseum & St.-Georgs-Kirche",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Modernes Museum zur kurdischen Kultur in der Festung. 50–100 TL p.P.",
        "notiz": "",
        "mapsSuche": "İçkale – Ahmed Arif Literaturmuseum & St.-Georgs-Kirche, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "14:30–16:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 5,
        "lat": 37.918,
        "lon": 40.243
      },
      {
        "id": "imp-soa-32",
        "kategorie": "sehenswuerdigkeit",
        "name": "Freizeit Altstadt & Basar",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Basar, Souvenirs.",
        "notiz": "",
        "mapsSuche": "Freizeit Altstadt & Basar, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "16:30–17:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 6,
        "lat": 37.9135,
        "lon": 40.236
      },
      {
        "id": "imp-soa-33",
        "kategorie": "aussicht",
        "name": "Sonnenuntergang Zehn-Bogen-Brücke (On Gözlü Köprü)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "⚠ Taxi für 04.10., 02:30 Uhr heute verbindlich vorbestellen!",
        "notiz": "",
        "mapsSuche": "Sonnenuntergang Zehn-Bogen-Brücke (On Gözlü Köprü), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 9,
        "lat": 37.885,
        "lon": 40.238
      },
      {
        "id": "imp-soa-34",
        "kategorie": "hotel",
        "name": "Rückflug – Taxi 02:30 → Flughafen (DIY)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Abholung 02:30 durch vorbestelltes Taxi (15 Min., 250–350 TL). Check-in 03:00, Rückflug 05:00.",
        "notiz": "",
        "mapsSuche": "Rückflug – Taxi 02:30 → Flughafen (DIY), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "02:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-04",
        "order": 0,
        "lat": 37.894,
        "lon": 40.201
      },
      {
        "id": "imp-soa-35",
        "kategorie": "kosten",
        "costCat": "anfahrt",
        "name": "Öffentl. Verkehr & Minibusse (2 Pers.)",
        "gebiet": "",
        "info": "Richtwert 41–59 €.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 50,
        "kostenIst": null,
        "day": null
      },
      {
        "id": "imp-soa-36",
        "kategorie": "kosten",
        "costCat": "anfahrt",
        "name": "Taxis (Airport, Mor Gabriel, Savur-/Dara-Runde, Drop-offs)",
        "gebiet": "",
        "info": "Richtwert 125–152 €.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 138,
        "kostenIst": null,
        "day": null
      },
      {
        "id": "imp-soa-37",
        "kategorie": "kosten",
        "costCat": "aktivitaet",
        "name": "Eintritte & Bootstour",
        "gebiet": "",
        "info": "Hasankeyf, Klöster, Medresen, Ahmed-Arif-Museum, Bootstour.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 50,
        "kostenIst": null,
        "day": null
      },
      {
        "id": "imp-soa-38",
        "kategorie": "kosten",
        "costCat": "unterkunft",
        "name": "Hotels (5 Nächte)",
        "gebiet": "",
        "info": "Richtwert 355–715 €.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 535,
        "kostenIst": null,
        "day": null
      }
    ],
    "days": {},
    "packing": [],
    "stays": [
      {
        "id": "seed-soa-stay-1",
        "ort": "Mardin",
        "name": "Mardin Osmanlı Konağı",
        "adresse": "Nähe 1. Cadde, Mardin",
        "checkin": "2026-09-29",
        "checkout": "2026-10-02",
        "inklusive": true,
        "hinweis": "Basis für den Süden: Mardin-Altstadt, Deyrulzafaran, Midyat/Mor Gabriel und Dara als Tagestouren – 3 Nächte, kein Umziehen."
      },
      {
        "id": "seed-soa-stay-2",
        "ort": "Diyarbakır",
        "name": "Demir Hotel",
        "adresse": "Altstadt Sur, Diyarbakır",
        "checkin": "2026-10-02",
        "checkout": "2026-10-04",
        "inklusive": true,
        "hinweis": "Letzte 2 Nächte, nah am Flughafen. 02:30-Taxi zum Rückflug (04.10.) am 03.10. über das Hotel vorbestellen."
      }
    ],
    "fxKurs": 56,
    "fxCode": "TRY",
    "personen": 3,
    "erledigt": false,
    "seedKey": "soa-tr-2026-09-2h"
  },
  {
    "id": "seed-nordsee-trip",
    "name": "Urlaub Nordsee / NL",
    "region": "Noordwijk aan Zee (Südholland)",
    "land": "Niederlande",
    "anreiseart": "auto",
    "von": "Celle",
    "nach": "Noordwijk aan Zee",
    "hinweise": "2 Personen · Auto · Euro. Sonnenuntergang ca. 17:10 (früh!). Busse (falls das Auto mal steht): OVpay mit deutscher Karte/Apple Pay, eine Karte pro Person. November: Öffnungszeiten von Beachclubs, Hortus u. a. vorab prüfen; Restaurants (Lab071, FRIS/Jopenkerk) reservieren.",
    "auto": {
      "km": 490,
      "preis": 1.8,
      "verbrauch": 9
    },
    "stay": {
      "name": "Alexander Hotel Noordwijk aan Zee",
      "adresse": "Noordwijk aan Zee",
      "checkin": "2026-11-04",
      "checkout": "2026-11-07",
      "inklusive": false,
      "hinweis": "3 Nächte. Spa, Sauna, Pool."
    },
    "start": "2026-11-04",
    "end": "2026-11-07",
    "personen": 2,
    "erledigt": false,
    "seedKey": "nordsee-nl-2026-11",
    "days": {
      "2026-11-04": {
        "title": "Anreise + Kasteel de Haar"
      },
      "2026-11-05": {
        "title": "Delft + Leiden"
      },
      "2026-11-06": {
        "title": "Dünen + Haarlem"
      },
      "2026-11-07": {
        "title": "Rückreise"
      }
    },
    "packing": [
      {
        "id": "nl-pk1",
        "text": "Regenjacke",
        "done": false
      },
      {
        "id": "nl-pk2",
        "text": "Feste Schuhe (Dünen, Strand)",
        "done": false
      },
      {
        "id": "nl-pk3",
        "text": "Badesachen (Hotel-Spa/Pool)",
        "done": false
      },
      {
        "id": "nl-pk4",
        "text": "Warme Kleidung (früher Sonnenuntergang)",
        "done": false
      }
    ],
    "checkliste": [
      {
        "id": "nl-c1",
        "text": "Kasteel de Haar: Online-Ticket Zeitfenster buchen (kasteeldehaar.nl)",
        "erledigt": false
      },
      {
        "id": "nl-c2",
        "text": "Alexander Hotel buchen: 3 Nächte, 04.–07.11. (alexanderhotel.nl)",
        "erledigt": false
      },
      {
        "id": "nl-c3",
        "text": "Lab071 Leiden reservieren (Do-Abend)",
        "erledigt": false
      },
      {
        "id": "nl-c4",
        "text": "FRIS / Jopenkerk Haarlem reservieren (Fr-Abend)",
        "erledigt": false
      },
      {
        "id": "nl-c5",
        "text": "Space Expo Ticket online (Fr-Plan B)",
        "erledigt": false
      },
      {
        "id": "nl-c6",
        "text": "Beachclubs Noordwijk: November-Öffnungszeiten checken (Branding, Witsand, O)",
        "erledigt": false
      },
      {
        "id": "nl-c7",
        "text": "Hortus Botanicus Leiden: Winteröffnung checken",
        "erledigt": false
      },
      {
        "id": "nl-c8",
        "text": "OVpay für Busse einrichten (deutsche Karte/Apple Pay, eine pro Person)",
        "erledigt": false
      }
    ],
    "items": [
      {
        "id": "nl-1",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kasteel de Haar",
        "gebiet": "Haarzuilens (bei Utrecht)",
        "info": "Größtes Schloss der Niederlande – um 1900 von Pierre Cuypers neugotisch wiederaufgebaut, mit prunkvollem Park.",
        "notiz": "Online-Zeitfenster-Ticket ~11:15 buchen (entspannter als 12:15). Park ab 9:00, Schloss ab 11:00, letzter Einlass 16:15. 20 Min. Fußweg Parkplatz ↔ Schloss.",
        "mapsSuche": "Kasteel de Haar, Haarzuilens",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "11:15",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-04",
        "order": 0,
        "lat": 52.1391,
        "lon": 4.9847,
        "besucht": false
      },
      {
        "id": "nl-2",
        "kategorie": "hotel",
        "name": "Check-in Alexander Hotel",
        "gebiet": "Noordwijk aan Zee",
        "info": "Check-in, 3 Nächte. Von Kasteel de Haar ca. 45 Min. Spa/Sauna/Pool.",
        "notiz": "",
        "mapsSuche": "Alexander Hotel Noordwijk aan Zee",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "17:00",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-04",
        "order": 1,
        "lat": 52.2404,
        "lon": 4.429,
        "besucht": false
      },
      {
        "id": "nl-3",
        "kategorie": "aussicht",
        "name": "Sonnenuntergang am Strand",
        "gebiet": "Noordwijk Boulevard",
        "info": "",
        "notiz": "Knapp nach Check-in – evtl. vom Boulevard aus.",
        "mapsSuche": "Noordwijk aan Zee Boulevard",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "17:10",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-04",
        "order": 2,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-4",
        "kategorie": "restaurant",
        "name": "Abendessen Beachclub Branding",
        "gebiet": "Noordwijk",
        "info": "",
        "notiz": "5 Min. vom Hotel. Alternativen: Witsand, Beachclub O. November-Öffnungszeiten vorab prüfen!",
        "mapsSuche": "Beachclub Branding Noordwijk",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-04",
        "order": 3,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-5",
        "kategorie": "sehenswuerdigkeit",
        "name": "Nieuwe Kerk Delft",
        "gebiet": "Delft",
        "info": "Grabkirche des niederländischen Königshauses; der Turm ist besteigbar.",
        "notiz": "",
        "mapsSuche": "Nieuwe Kerk Delft",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "10:00",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 0,
        "lat": 52.0121,
        "lon": 4.3578,
        "besucht": false
      },
      {
        "id": "nl-6",
        "kategorie": "sehenswuerdigkeit",
        "name": "Oude Kerk Delft",
        "gebiet": "Delft",
        "info": "Schiefer Turm; hier ist u. a. Jan Vermeer begraben.",
        "notiz": "",
        "mapsSuche": "Oude Kerk Delft",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 1,
        "lat": 52.0131,
        "lon": 4.355,
        "besucht": false
      },
      {
        "id": "nl-7",
        "kategorie": "sehenswuerdigkeit",
        "name": "Museum Prinsenhof Delft",
        "gebiet": "Delft",
        "info": "Ehem. Kloster; hier wurde Wilhelm von Oranien 1584 ermordet – die Einschusslöcher sind noch zu sehen.",
        "notiz": "",
        "mapsSuche": "Museum Prinsenhof Delft",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 2,
        "lat": 52.0129,
        "lon": 4.3545,
        "besucht": false
      },
      {
        "id": "nl-8",
        "kategorie": "sehenswuerdigkeit",
        "name": "Grachtenfahrt Delft",
        "gebiet": "Delft",
        "info": "Kleine Bootstour durch die Grachten.",
        "notiz": "",
        "mapsSuche": "Rondvaart Delft",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 3,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-9",
        "kategorie": "restaurant",
        "name": "Mittagessen Delft",
        "gebiet": "Delft",
        "info": "",
        "notiz": "Optionen: HANNO, Flow Foodbar, Huszár, Kek; vegetarisch: Wildgroei.",
        "mapsSuche": "Delft Markt",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 4,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-10",
        "kategorie": "aussicht",
        "name": "Burcht van Leiden",
        "gebiet": "Leiden",
        "info": "Runde Ringburg auf einem Hügel – Panorama über Leiden.",
        "notiz": "Parken: Garenmarkt oder Morssingel.",
        "mapsSuche": "Burcht van Leiden",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "14:30",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 5,
        "lat": 52.1589,
        "lon": 4.4946,
        "besucht": false
      },
      {
        "id": "nl-11",
        "kategorie": "sehenswuerdigkeit",
        "name": "Pieterskerk Leiden",
        "gebiet": "Leiden",
        "info": "Spätgotische Kirche; Verbindung zu den Pilgervätern (Mayflower).",
        "notiz": "",
        "mapsSuche": "Pieterskerk Leiden",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 6,
        "lat": 52.157,
        "lon": 4.4886,
        "besucht": false
      },
      {
        "id": "nl-12",
        "kategorie": "sehenswuerdigkeit",
        "name": "Molen de Valk",
        "gebiet": "Leiden",
        "info": "Windmühlen-Museum in einer historischen Turmmühle.",
        "notiz": "",
        "mapsSuche": "Molen de Valk Leiden",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 7,
        "lat": 52.1636,
        "lon": 4.4863,
        "besucht": false
      },
      {
        "id": "nl-13",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hortus Botanicus Leiden",
        "gebiet": "Leiden",
        "info": "Einer der ältesten botanischen Gärten der Welt (1590).",
        "notiz": "Winteröffnung checken!",
        "mapsSuche": "Hortus Botanicus Leiden",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 8,
        "lat": 52.1572,
        "lon": 4.4847,
        "besucht": false
      },
      {
        "id": "nl-14",
        "kategorie": "restaurant",
        "name": "Abendessen Leiden",
        "gebiet": "Leiden",
        "info": "",
        "notiz": "Lab071 (RESERVIEREN!), Sophie Kattencafé, Freddy's Gastrobar, Pakhuis. Danach zurück nach Noordwijk zum Sonnenuntergang.",
        "mapsSuche": "Lab071 Leiden",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-05",
        "order": 9,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-15",
        "kategorie": "wanderung",
        "name": "Dünenwanderung Noordduinen",
        "gebiet": "Noordwijk",
        "info": "Ab Hotel über die Noordduinen, Rückweg am Strand (ca. 7–8 km).",
        "notiz": "Alternative Süd: Zandhagedisroute ab Randweg (8 km, GPS nötig). Regenjacke + feste Schuhe.",
        "mapsSuche": "Noordduinen Noordwijk",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "09:00",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 0,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-16",
        "kategorie": "sehenswuerdigkeit",
        "name": "Museum Engelandvaarders",
        "gebiet": "Noordwijk",
        "info": "Museum zu den „Engelandvaarders“ – Menschen, die im 2. Weltkrieg übers Meer nach England flohen.",
        "notiz": "Di–Fr 10:30–16:30.",
        "mapsSuche": "Museum Engelandvaarders Noordwijk",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 1,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-17",
        "kategorie": "restaurant",
        "name": "Mittagessen Noordwijk",
        "gebiet": "Noordwijk",
        "info": "",
        "notiz": "Im Hotel oder in Noordwijk: Open-Doors, Fratelli.",
        "mapsSuche": "Noordwijk aan Zee",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 2,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-18",
        "kategorie": "sehenswuerdigkeit",
        "name": "Grote Kerk (St. Bavo) Haarlem",
        "gebiet": "Haarlem",
        "info": "Spätgotische Kirche am Grote Markt mit der berühmten Müller-Orgel, auf der schon Mozart und Händel spielten.",
        "notiz": "NICHT die neue Kathedrale Basiliek St. Bavo verwechseln! Goldene Stunde 15:30–17:10.",
        "mapsSuche": "Grote Kerk Haarlem Grote Markt",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "13:45",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 3,
        "lat": 52.3814,
        "lon": 4.6366,
        "besucht": false
      },
      {
        "id": "nl-19",
        "kategorie": "sehenswuerdigkeit",
        "name": "Amsterdamse Poort Haarlem",
        "gebiet": "Haarlem",
        "info": "Einziges erhaltenes mittelalterliches Stadttor Haarlems.",
        "notiz": "",
        "mapsSuche": "Amsterdamse Poort Haarlem",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 4,
        "lat": 52.3792,
        "lon": 4.6457,
        "besucht": false
      },
      {
        "id": "nl-20",
        "kategorie": "sehenswuerdigkeit",
        "name": "Molen De Adriaan",
        "gebiet": "Haarlem",
        "info": "Markante Windmühle am Fluss Spaarne.",
        "notiz": "",
        "mapsSuche": "Molen De Adriaan Haarlem",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 5,
        "lat": 52.3836,
        "lon": 4.6397,
        "besucht": false
      },
      {
        "id": "nl-21",
        "kategorie": "restaurant",
        "name": "Jopenkerk Haarlem",
        "gebiet": "Haarlem",
        "info": "Brauerei in einer alten Kirche – Fotospot und Essen/Bier.",
        "notiz": "Abendessen hier oder FRIS (RESERVIEREN!). Kaffee/Snack: Coffee Spot Roos, Cleef.",
        "mapsSuche": "Jopenkerk Haarlem",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-06",
        "order": 6,
        "lat": 52.3813,
        "lon": 4.631,
        "besucht": false
      },
      {
        "id": "nl-22",
        "kategorie": "aussicht",
        "name": "Vuurtoren / Strandspaziergang",
        "gebiet": "Noordwijk",
        "info": "Nach dem Frühstück kurzer Spaziergang zum Leuchtturm bzw. am Strand.",
        "notiz": "",
        "mapsSuche": "Vuurtoren Noordwijk",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "09:30",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-07",
        "order": 0,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-23",
        "kategorie": "stadt",
        "name": "Mittagsstopp Osnabrück Altstadt",
        "gebiet": "Osnabrück",
        "info": "Abfahrt ca. 10:30–11:00; Mittagsstopp in der Altstadt (~12:30–14:00). Ankunft Celle ca. 16:30.",
        "notiz": "",
        "mapsSuche": "Osnabrück Altstadt",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "12:30",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": "2026-11-07",
        "order": 1,
        "lat": 52.2781,
        "lon": 8.043,
        "besucht": false
      },
      {
        "id": "nl-24",
        "kategorie": "sehenswuerdigkeit",
        "name": "Space Expo Noordwijk",
        "gebiet": "Noordwijk",
        "info": "ESA-Besucherzentrum zur Raumfahrt, ca. 10 Min. vom Hotel.",
        "notiz": "PLAN B für Freitag, falls Haarlem nicht klappt. Di–So 10:00–17:00, Tickets online mit Zeitfenster.",
        "mapsSuche": "Space Expo Noordwijk",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": null,
        "order": 0,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-25",
        "kategorie": "aussicht",
        "name": "Strand- & Wellness-Tag (Hotel-Spa)",
        "gebiet": "Noordwijk",
        "info": "",
        "notiz": "PLAN B für Freitag: Spa, Sauna, Pool im Hotel + Strand.",
        "mapsSuche": "Alexander Hotel Noordwijk",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": "",
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "",
        "day": null,
        "order": 1,
        "lat": null,
        "lon": null,
        "besucht": false
      },
      {
        "id": "nl-b1",
        "kategorie": "kosten",
        "costCat": "anfahrt",
        "name": "Sprit (Auto, hin/zurück, ~490 km)",
        "gebiet": "",
        "info": "",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 159,
        "kostenIst": null,
        "day": null
      }
    ]
  }
];
