/*
  seedReisen.js — vorgefertigte Reisen, die beim ERSTEN Start (nach Deploy)
  EINMALIG in die App eingespielt werden.
  ---------------------------------------------------------------------------
  • Wird NICHT über den normalen Import geladen, sondern von App.jsx über
    seedeReisen() genau einmal pro Gerät ergänzt (Merker in localStorage:
    "chds-seeds-applied", pro seedKey).
  • Fügt nur HINZU – vorhandene, selbst geplante Reisen bleiben unberührt.
  • Löscht der Nutzer eine Seed-Reise, kommt sie NICHT zurück (seedKey gilt
    als erledigt). Neue Seeds mit neuem seedKey werden später einmalig ergänzt.
  • Doppelt-Schutz: existiert bereits eine Reise mit gleichem Namen+Startdatum
    (z. B. früher manuell importiert), wird der Seed übersprungen.

  Format je Reise = exakt das App-Trip-Objekt (wie createTrip erzeugt),
  zusätzlich: seedKey (stabil), erledigt (Abhaken-Status) und – bei Rundreisen –
  stays[] (Hotels pro Nacht, Banner oben je Tag) sowie fxKurs/fxCode (Währung).
  Nichts erfunden: Inhalte stammen aus den abgestimmten Reiseplänen; Hotels und
  Kurs (1 € ≈ 56 TL) aus deinen Angaben. Koordinaten sind Näherungswerte
  (pro Punkt ist die Kartensuche „Name, Ort" hinterlegt).
*/

export const SEED_TRIPS = [
  {
    "id": "imp-ams-trip",
    "name": "Amsterdam & Umgebung",
    "region": "Amsterdam",
    "land": "Niederlande",
    "anreiseart": "auto",
    "von": "Celle",
    "nach": "Amsterdam",
    "hinweise": "Anne Frank Haus unbedingt vorab online buchen. Grachtenfahrt: Lovers Canal Cruises. Rückfahrt mit Mittagsstopp in Osnabrück.",
    "auto": {
      "km": "",
      "preis": 1.8,
      "verbrauch": 9
    },
    "stay": {
      "name": "Grand Hotel Amrâth Amsterdam",
      "adresse": "Prins Hendrikkade 108, Amsterdam",
      "checkin": "2026-11-04",
      "checkout": "2026-11-07"
    },
    "start": "2026-11-04",
    "end": "2026-11-07",
    "items": [
      {
        "id": "imp-ams-1",
        "kategorie": "sehenswuerdigkeit",
        "name": "Vesting Naarden (Sternfestung)",
        "gebiet": "Naarden, Niederlande",
        "info": "Sternförmige Festungsstadt – erster Stopp auf der Anfahrt von Celle.",
        "notiz": "",
        "mapsSuche": "Vesting Naarden (Sternfestung), Naarden, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-04",
        "order": 0,
        "lat": 52.2958,
        "lon": 5.1619
      },
      {
        "id": "imp-ams-2",
        "kategorie": "hotel",
        "name": "Check-in Grand Hotel Amrâth Amsterdam",
        "gebiet": "Amsterdam, Niederlande",
        "info": "Prins Hendrikkade 108. Check-in nach Ankunft in Amsterdam.",
        "notiz": "",
        "mapsSuche": "Check-in Grand Hotel Amrâth Amsterdam, Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-04",
        "order": 1,
        "lat": 52.3765,
        "lon": 4.902
      },
      {
        "id": "imp-ams-3",
        "kategorie": "sehenswuerdigkeit",
        "name": "Anne Frank Haus",
        "gebiet": "Amsterdam, Niederlande",
        "info": "VORAB ONLINE BUCHEN! Tickets sind schnell ausverkauft.",
        "notiz": "",
        "mapsSuche": "Anne Frank Haus, Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-05",
        "order": 0,
        "lat": 52.3752,
        "lon": 4.884
      },
      {
        "id": "imp-ams-4",
        "kategorie": "sehenswuerdigkeit",
        "name": "Amsterdam erkunden (Altstadt & Grachten)",
        "gebiet": "Amsterdam, Niederlande",
        "info": "Bummel durch Zentrum, Grachtengürtel, Jordaan.",
        "notiz": "",
        "mapsSuche": "Amsterdam erkunden (Altstadt & Grachten), Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-05",
        "order": 1,
        "lat": 52.3731,
        "lon": 4.8926
      },
      {
        "id": "imp-ams-5",
        "kategorie": "sehenswuerdigkeit",
        "name": "Grachtenfahrt – Lovers Canal Cruises",
        "gebiet": "Amsterdam, Niederlande",
        "info": "Bootstour über die Grachten.",
        "notiz": "",
        "mapsSuche": "Grachtenfahrt – Lovers Canal Cruises, Amsterdam, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-05",
        "order": 2,
        "lat": 52.3785,
        "lon": 4.9005
      },
      {
        "id": "imp-ams-6",
        "kategorie": "sehenswuerdigkeit",
        "name": "Haarlem – Grote Markt",
        "gebiet": "Haarlem, Niederlande",
        "info": "Historischer Marktplatz mit St.-Bavo-Kirche.",
        "notiz": "",
        "mapsSuche": "Haarlem – Grote Markt, Haarlem, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 0,
        "lat": 52.3813,
        "lon": 4.6367
      },
      {
        "id": "imp-ams-7",
        "kategorie": "sehenswuerdigkeit",
        "name": "Frans Hals Museum",
        "gebiet": "Haarlem, Niederlande",
        "info": "Goldenes Zeitalter, Werke von Frans Hals.",
        "notiz": "",
        "mapsSuche": "Frans Hals Museum, Haarlem, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 1,
        "lat": 52.3772,
        "lon": 4.633
      },
      {
        "id": "imp-ams-8",
        "kategorie": "restaurant",
        "name": "Jopenkerk (Brauerei in Kirche)",
        "gebiet": "Haarlem, Niederlande",
        "info": "Brauerei-Gasthaus in einer alten Kirche – Mittag/Pause.",
        "notiz": "",
        "mapsSuche": "Jopenkerk (Brauerei in Kirche), Haarlem, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 2,
        "lat": 52.382,
        "lon": 4.633
      },
      {
        "id": "imp-ams-9",
        "kategorie": "wanderung",
        "name": "Bloemendaal aan Zee – Dünenwanderung",
        "gebiet": "Bloemendaal aan Zee, Niederlande",
        "info": "Dünen- und Strandwanderung an der Nordseeküste.",
        "notiz": "",
        "mapsSuche": "Bloemendaal aan Zee – Dünenwanderung, Bloemendaal aan Zee, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 3,
        "lat": 52.41,
        "lon": 4.535
      },
      {
        "id": "imp-ams-10",
        "kategorie": "restaurant",
        "name": "Café Tijn Akersloot",
        "gebiet": "Bloemendaal aan Zee, Niederlande",
        "info": "Strandcafé zum Ausklang.",
        "notiz": "",
        "mapsSuche": "Café Tijn Akersloot, Bloemendaal aan Zee, Niederlande",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-06",
        "order": 4,
        "lat": 52.409,
        "lon": 4.536
      },
      {
        "id": "imp-ams-11",
        "kategorie": "restaurant",
        "name": "Osnabrück – Mittagessen (Rückfahrt)",
        "gebiet": "Osnabrück, Deutschland",
        "info": "Zwischenstopp auf dem Rückweg nach Celle.",
        "notiz": "",
        "mapsSuche": "Osnabrück – Mittagessen (Rückfahrt), Osnabrück, Deutschland",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-11-07",
        "order": 0,
        "lat": 52.279,
        "lon": 8.043
      }
    ],
    "days": {},
    "packing": [],
    "seedKey": "ams-nl-2026-11",
    "erledigt": false
  },
  {
    "id": "imp-soa-trip",
    "name": "Rundreise Südostanatolien",
    "region": "Diyarbakır",
    "land": "Türkei",
    "anreiseart": "flug",
    "von": "",
    "nach": "Diyarbakır",
    "hinweise": "2 Personen · Bus, Minibus & Taxi · Kurs 1 € ≈ 56 TL. WICHTIG: Taxi für Rückflug (04.10., 02:30) am 03.10. über Hotel vorbestellen. NOVH-Bus Mardin→Diyarbakır (02.10., 14:00) prüfen/buchen. Hotels in Mardin früh buchen. Bargeld in kleinen Scheinen (50/100/200 TL). Rutschfeste Schuhe, bedeckende Kleidung für religiöse Stätten.",
    "auto": {
      "km": "",
      "preis": 1.8,
      "verbrauch": 9
    },
    "stay": {
      "name": "Wechselnde Hotels: Diyarbakır · Midyat · Mardin",
      "adresse": "",
      "checkin": "2026-09-29",
      "checkout": "2026-10-04"
    },
    "start": "2026-09-29",
    "end": "2026-10-04",
    "items": [
      {
        "id": "imp-soa-1",
        "kategorie": "hotel",
        "name": "Check-in Hotel – Altstadt Sur",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Landung 12:00 (DIY), Taxi nach Sur (15 Min., 250–350 TL).",
        "notiz": "",
        "mapsSuche": "Check-in Hotel – Altstadt Sur, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "12:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 0,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-2",
        "kategorie": "sehenswuerdigkeit",
        "name": "Große Moschee (Ulu Camii)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Große Moschee (Ulu Camii), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "nachmittags",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 1,
        "lat": 37.9128,
        "lon": 40.2378
      },
      {
        "id": "imp-soa-3",
        "kategorie": "restaurant",
        "name": "Hasan Paşa Hanı",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Kaffee im historischen Innenhof.",
        "notiz": "",
        "mapsSuche": "Hasan Paşa Hanı, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 2,
        "lat": 37.913,
        "lon": 40.2383
      },
      {
        "id": "imp-soa-4",
        "kategorie": "sehenswuerdigkeit",
        "name": "Armenische Kirche Surp Giragos",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Armenische Kirche Surp Giragos, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 3,
        "lat": 37.9143,
        "lon": 40.2358
      },
      {
        "id": "imp-soa-5",
        "kategorie": "sehenswuerdigkeit",
        "name": "Vier-Füße-Minarett (Dört Ayaklı Minare)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Vier-Füße-Minarett (Dört Ayaklı Minare), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 4,
        "lat": 37.9124,
        "lon": 40.2352
      },
      {
        "id": "imp-soa-6",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hevsel-Gärten (UNESCO-Welterbe)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Spaziergang durch die terrassierten Gärten am Tigris.",
        "notiz": "",
        "mapsSuche": "Hevsel-Gärten (UNESCO-Welterbe), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 5,
        "lat": 37.905,
        "lon": 40.245
      },
      {
        "id": "imp-soa-7",
        "kategorie": "aussicht",
        "name": "Sonnenuntergang Stadtmauer – Keçi Burcu",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Blick auf Hevsel-Gärten & Tigristal.",
        "notiz": "",
        "mapsSuche": "Sonnenuntergang Stadtmauer – Keçi Burcu, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "18:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 6,
        "lat": 37.906,
        "lon": 40.2415
      },
      {
        "id": "imp-soa-8",
        "kategorie": "restaurant",
        "name": "Abendessen in Sur (Ciğer/Diyarbakır-Kebab)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Abendessen in Sur (Ciğer/Diyarbakır-Kebab), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "abends",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-29",
        "order": 7,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-9",
        "kategorie": "sehenswuerdigkeit",
        "name": "Heimatort Batman besuchen",
        "gebiet": "Batman, Türkei",
        "info": "Familie/Bekannte treffen, frühes Mittagessen. Minibus ab Diyarbakır (Doğu İlçe Otogarı), 1:15 Std.",
        "notiz": "",
        "mapsSuche": "Heimatort Batman besuchen, Batman, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "09:00–12:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 0,
        "lat": 37.8812,
        "lon": 41.1351
      },
      {
        "id": "imp-soa-10",
        "kategorie": "fotospot",
        "name": "Malabadi-Brücke (Foto-Stopp)",
        "gebiet": "Silvan, Türkei",
        "info": "Größte Steinbogenbrücke der Welt (12. Jh.). 15 Min. Umweg, frei.",
        "notiz": "",
        "mapsSuche": "Malabadi-Brücke (Foto-Stopp), Silvan, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "12:15",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 1,
        "lat": 38.087,
        "lon": 41.025
      },
      {
        "id": "imp-soa-11",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hasankeyf – Arkeopark & Museum",
        "gebiet": "Hasankeyf, Türkei",
        "info": "Gepäck am Museum/Ticketcenter deponieren. Eintritt 3 €.",
        "notiz": "",
        "mapsSuche": "Hasankeyf – Arkeopark & Museum, Hasankeyf, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "13:30–16:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 2,
        "lat": 37.7146,
        "lon": 41.414
      },
      {
        "id": "imp-soa-12",
        "kategorie": "sehenswuerdigkeit",
        "name": "Tigris-Bootstour Hasankeyf",
        "gebiet": "Hasankeyf, Türkei",
        "info": "1–1,5 Std., vor Ort am Steg buchen.",
        "notiz": "",
        "mapsSuche": "Tigris-Bootstour Hasankeyf, Hasankeyf, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 3,
        "lat": 37.7146,
        "lon": 41.414
      },
      {
        "id": "imp-soa-13",
        "kategorie": "hotel",
        "name": "Check-in Steinhaus (Konak)",
        "gebiet": "Midyat, Türkei",
        "info": "Letzter Minibus Hasankeyf→Midyat 16:30 (45 Min., 100–200 TL p.P.).",
        "notiz": "",
        "mapsSuche": "Check-in Steinhaus (Konak), Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:15",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 4,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-14",
        "kategorie": "sehenswuerdigkeit",
        "name": "Abendspaziergang Eski Midyat (Alt-Midyat)",
        "gebiet": "Midyat, Türkei",
        "info": "Verlassene Höhlenhäuser & versteckte Kirchen. Frei, ~30 Min.",
        "notiz": "",
        "mapsSuche": "Abendspaziergang Eski Midyat (Alt-Midyat), Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "18:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 5,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-15",
        "kategorie": "restaurant",
        "name": "Abendessen Gelüşke Hanı",
        "gebiet": "Midyat, Türkei",
        "info": "Historisches Ambiente.",
        "notiz": "",
        "mapsSuche": "Abendessen Gelüşke Hanı, Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-09-30",
        "order": 6,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-16",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kloster Mor Gabriel (Syrisch-Orthodox)",
        "gebiet": "Midyat, Türkei",
        "info": "Taxi ab Hotel (Festpreis 2.000–2.500 TL inkl. 1,5 Std. Wartezeit). Eintritt 200–300 TL p.P.; Knie/Schultern bedeckt.",
        "notiz": "",
        "mapsSuche": "Kloster Mor Gabriel (Syrisch-Orthodox), Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "09:00–10:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 0,
        "lat": 37.34,
        "lon": 41.472
      },
      {
        "id": "imp-soa-17",
        "kategorie": "sehenswuerdigkeit",
        "name": "Midyat – Konuk Evi & Telkari-Gassen",
        "gebiet": "Midyat, Türkei",
        "info": "Silberschmiede (Telkari), Konuk Evi 100 TL.",
        "notiz": "",
        "mapsSuche": "Midyat – Konuk Evi & Telkari-Gassen, Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "11:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 1,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-18",
        "kategorie": "restaurant",
        "name": "Mittagessen Midyat Aş Evi",
        "gebiet": "Midyat, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Mittagessen Midyat Aş Evi, Midyat, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "12:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 2,
        "lat": 37.4179,
        "lon": 41.362
      },
      {
        "id": "imp-soa-19",
        "kategorie": "hotel",
        "name": "Check-in Hotel Mardin Altstadt (1. Cadde)",
        "gebiet": "Mardin, Türkei",
        "info": "Minibus Midyat→Mardin 13:30 (1:15, 195–250 TL p.P.).",
        "notiz": "",
        "mapsSuche": "Check-in Hotel Mardin Altstadt (1. Cadde), Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "14:45",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 3,
        "lat": 37.3125,
        "lon": 40.737
      },
      {
        "id": "imp-soa-20",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kasımiye-Medrese & Kırklar-Kirche",
        "gebiet": "Mardin, Türkei",
        "info": "Kasımiye 80 TL, Kırklar 70 TL.",
        "notiz": "",
        "mapsSuche": "Kasımiye-Medrese & Kırklar-Kirche, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "15:00–16:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 4,
        "lat": 37.3075,
        "lon": 40.726
      },
      {
        "id": "imp-soa-21",
        "kategorie": "aussicht",
        "name": "Zinciriye-Medrese – Sonnenuntergang & Panorama",
        "gebiet": "Mardin, Türkei",
        "info": "Panoramablick über die mesopotamische Tiefebene. Eintritt 100 TL.",
        "notiz": "",
        "mapsSuche": "Zinciriye-Medrese – Sonnenuntergang & Panorama, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:00–18:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 5,
        "lat": 37.3135,
        "lon": 40.7385
      },
      {
        "id": "imp-soa-22",
        "kategorie": "restaurant",
        "name": "Abendessen Dachterrasse 1. Cadde",
        "gebiet": "Mardin, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Abendessen Dachterrasse 1. Cadde, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "abends",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-01",
        "order": 6,
        "lat": 37.3125,
        "lon": 40.737
      },
      {
        "id": "imp-soa-23",
        "kategorie": "sehenswuerdigkeit",
        "name": "Kloster Deyrulzafaran (Safran-Kloster)",
        "gebiet": "Mardin, Türkei",
        "info": "Taxirunde Festpreis 3.500–4.000 TL inkl. Wartezeiten & Otogar. Führung & unterirdischer Sonnentempel. 200–300 TL p.P.",
        "notiz": "",
        "mapsSuche": "Kloster Deyrulzafaran (Safran-Kloster), Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "08:15",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 0,
        "lat": 37.307,
        "lon": 40.788
      },
      {
        "id": "imp-soa-24",
        "kategorie": "sehenswuerdigkeit",
        "name": "Savur",
        "gebiet": "Savur, Türkei",
        "info": "Authentisches kurdisches Städtchen mit jüdischer Synagoge (eine der ältesten der Türkei). ~1 Std. Stopp, frei.",
        "notiz": "",
        "mapsSuche": "Savur, Savur, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 1,
        "lat": 37.548,
        "lon": 40.895
      },
      {
        "id": "imp-soa-25",
        "kategorie": "sehenswuerdigkeit",
        "name": "Antike Stadt Dara",
        "gebiet": "Oğuz, Mardin, Türkei",
        "info": "Zisternen & Felsnekropole (falls Zeit bleibt), frei.",
        "notiz": "",
        "mapsSuche": "Antike Stadt Dara, Oğuz, Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 2,
        "lat": 37.177,
        "lon": 40.948
      },
      {
        "id": "imp-soa-26",
        "kategorie": "restaurant",
        "name": "Mittagessen Yenişehir (Mardin Çırağan)",
        "gebiet": "Mardin, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Mittagessen Yenişehir (Mardin Çırağan), Mardin, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "13:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 3,
        "lat": 37.328,
        "lon": 40.735
      },
      {
        "id": "imp-soa-27",
        "kategorie": "hotel",
        "name": "Check-in Hotel Diyarbakır",
        "gebiet": "Diyarbakır, Türkei",
        "info": "NOVH-Bus Mardin→Diyarbakır 14:00 (1:20, 420–500 TL p.P.).",
        "notiz": "",
        "mapsSuche": "Check-in Hotel Diyarbakır, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "15:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 4,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-28",
        "kategorie": "sehenswuerdigkeit",
        "name": "Hamam-Besuch (Abend)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Entspannter Abend in Diyarbakır.",
        "notiz": "",
        "mapsSuche": "Hamam-Besuch (Abend), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "abends",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-02",
        "order": 5,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-29",
        "kategorie": "sehenswuerdigkeit",
        "name": "Römisches Grenzkastell Zerzevan Kalesi",
        "gebiet": "Çınar, Diyarbakır, Türkei",
        "info": "Inkl. Mithras-Heiligtum. Anfahrt Stadtbus ÇM (KentKart) ab Doğu İlçe Garajı.",
        "notiz": "",
        "mapsSuche": "Römisches Grenzkastell Zerzevan Kalesi, Çınar, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "10:00–12:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 0,
        "lat": 37.552,
        "lon": 40.48
      },
      {
        "id": "imp-soa-30",
        "kategorie": "restaurant",
        "name": "Mittagessen Altstadt Diyarbakır",
        "gebiet": "Diyarbakır, Türkei",
        "info": "",
        "notiz": "",
        "mapsSuche": "Mittagessen Altstadt Diyarbakır, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "13:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 1,
        "lat": 37.9139,
        "lon": 40.2306
      },
      {
        "id": "imp-soa-31",
        "kategorie": "sehenswuerdigkeit",
        "name": "İçkale – Ahmed Arif Literaturmuseum & St.-Georgs-Kirche",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Modernes Museum zur kurdischen Kultur in der Festung. 50–100 TL p.P.",
        "notiz": "",
        "mapsSuche": "İçkale – Ahmed Arif Literaturmuseum & St.-Georgs-Kirche, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "14:30–16:00",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 2,
        "lat": 37.918,
        "lon": 40.243
      },
      {
        "id": "imp-soa-32",
        "kategorie": "sehenswuerdigkeit",
        "name": "Freizeit Altstadt & Basar",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Basar, Souvenirs.",
        "notiz": "",
        "mapsSuche": "Freizeit Altstadt & Basar, Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "16:30–17:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 3,
        "lat": 37.9135,
        "lon": 40.236
      },
      {
        "id": "imp-soa-33",
        "kategorie": "aussicht",
        "name": "Sonnenuntergang Zehn-Bogen-Brücke (On Gözlü Köprü)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "⚠ Taxi für 04.10., 02:30 Uhr heute verbindlich vorbestellen!",
        "notiz": "",
        "mapsSuche": "Sonnenuntergang Zehn-Bogen-Brücke (On Gözlü Köprü), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "17:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-03",
        "order": 4,
        "lat": 37.885,
        "lon": 40.238
      },
      {
        "id": "imp-soa-34",
        "kategorie": "hotel",
        "name": "Rückflug – Taxi 02:30 → Flughafen (DIY)",
        "gebiet": "Diyarbakır, Türkei",
        "info": "Abholung 02:30 durch vorbestelltes Taxi (15 Min., 250–350 TL). Check-in 03:00, Rückflug 05:00.",
        "notiz": "",
        "mapsSuche": "Rückflug – Taxi 02:30 → Flughafen (DIY), Diyarbakır, Türkei",
        "kostenHinweis": "",
        "kosten": null,
        "kostenIst": null,
        "prio": null,
        "zeit": "02:30",
        "fahrzeit": "",
        "season": "",
        "weather": "any",
        "day": "2026-10-04",
        "order": 0,
        "lat": 37.894,
        "lon": 40.201
      },
      {
        "id": "imp-soa-35",
        "kategorie": "kosten",
        "costCat": "anfahrt",
        "name": "Öffentl. Verkehr & Minibusse (2 Pers.)",
        "gebiet": "",
        "info": "Richtwert 41–59 €.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 50,
        "kostenIst": null,
        "day": null
      },
      {
        "id": "imp-soa-36",
        "kategorie": "kosten",
        "costCat": "anfahrt",
        "name": "Taxis (Airport, Mor Gabriel, Savur-/Dara-Runde, Drop-offs)",
        "gebiet": "",
        "info": "Richtwert 125–152 €.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 138,
        "kostenIst": null,
        "day": null
      },
      {
        "id": "imp-soa-37",
        "kategorie": "kosten",
        "costCat": "aktivitaet",
        "name": "Eintritte & Bootstour",
        "gebiet": "",
        "info": "Hasankeyf, Klöster, Medresen, Ahmed-Arif-Museum, Bootstour.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 50,
        "kostenIst": null,
        "day": null
      },
      {
        "id": "imp-soa-38",
        "kategorie": "kosten",
        "costCat": "unterkunft",
        "name": "Hotels (5 Nächte)",
        "gebiet": "",
        "info": "Richtwert 355–715 €.",
        "mapsSuche": "",
        "kostenHinweis": "",
        "kosten": 535,
        "kostenIst": null,
        "day": null
      }
    ],
    "days": {},
    "packing": [],
    "stays": [
      {
        "id": "seed-soa-stay-1",
        "ort": "Diyarbakır",
        "name": "Demir Hotel",
        "adresse": "Altstadt Sur, Diyarbakır",
        "checkin": "2026-09-29",
        "checkout": "2026-09-30",
        "inklusive": true,
        "hinweis": "Direkt an der Altstadt Sur; voll befahrbare Straße für den Gepäcktransport."
      },
      {
        "id": "seed-soa-stay-2",
        "ort": "Midyat",
        "name": "Mons Masius Boutique Hotel",
        "adresse": "Historischer Kern, Midyat",
        "checkin": "2026-09-30",
        "checkout": "2026-10-01",
        "inklusive": true,
        "hinweis": "Mitten im historischen Kern; kurzer Weg zum Konuk Evi und schnelle Taxi-Abfahrt morgens nach Mor Gabriel."
      },
      {
        "id": "seed-soa-stay-3",
        "ort": "Mardin",
        "name": "Mardin Osmanlı Konağı",
        "adresse": "Nähe 1. Cadde, Mardin",
        "checkin": "2026-10-01",
        "checkout": "2026-10-02",
        "inklusive": true,
        "hinweis": "Nah an der 1. Cadde; keine weiten Treppenmärsche mit Gepäck, perfekter Startpunkt für die Taxi-Tour nach Deyrulzafaran/Dara und zum Otogar."
      },
      {
        "id": "seed-soa-stay-4",
        "ort": "Diyarbakır",
        "name": "Demir Hotel",
        "adresse": "Altstadt Sur, Diyarbakır",
        "checkin": "2026-10-02",
        "checkout": "2026-10-04",
        "inklusive": true,
        "hinweis": "Rückkehr für die letzten 2 Nächte; das bestellte Taxi um 02:30 Uhr zum Flughafen fährt ab hier (voll befahrbare Straße)."
      }
    ],
    "fxKurs": 56,
    "fxCode": "TRY",
    "seedKey": "soa-tr-2026-09",
    "erledigt": false
  }
];
